fix: terraform-planの結果チェックロジックを修正 (#9)
* fix: terraform-planの結果チェックロジックを修正

terraform-planの結果が成功またはスキップでない場合にエラーメッセージを表示し、ワークフローを失敗として終了するように変更しました。成功時には「Success!!」と表示するようにしました。

* fix: 成功チェックのロジックを改善

pull-request-other.yamlの成功条件を修正し、check-documentationの結果に基づいてワークフローの成功を判断するようにしました。これにより、失敗またはキャンセルされた場合に適切にエラーメッセージを表示するようになりました。

diff --git a/.github/workflows/pull-request-other.yaml b/.github/workflows/pull-request-other.yaml
--- a/.github/workflows/pull-request-other.yaml
+++ b/.github/workflows/pull-request-other.yaml
@@ -50,8 +50,17 @@ jobs:
 
   success:
     needs: check-documentation
-    if: ${{ !failure() }}
+    if: ${{ always() }}
     runs-on: ubuntu-latest
 
     steps:
-      - run: echo "Success!!"
+      - name: Check job result
+        run: |
+          RESULT="${{ needs.check-documentation.result }}"
+          if [[ $RESULT != "success" && $RESULT != "skipped" ]]; then
+            echo "This workflow failed or was cancelled!"
+            exit 1
+          fi
+
+          echo "Success!!"
+          exit 0
