Feat/enable_aqua_checksum (#43)
* feat: 成功確認ジョブを追加

terraform-deploy.yamlに成功確認ジョブを追加しました。このジョブは、terraform-apply、extract-created-lxc、ansible-for-proxmox-lxcの各ジョブの結果を確認し、いずれかが失敗またはキャンセルされた場合にエラーメッセージを出力します。全て成功した場合は「Success!!」と表示します。

* fix: チェックサム設定を有効化

aqua.yamlファイルのチェックサム設定を有効にし、関連するオプションをコメント解除しました。

* feat: aqua-checksums.jsonを更新するワークフローを追加

新しいGitHub Actionsワークフローを追加し、プルリクエスト時にaqua-checksums.jsonを更新する処理を実行します。具体的には、リポジトリのチェックアウト、aquaのインストール、チェックサムの修正、コミットおよびプッシュを行います。

* feat: 更新時の排他制御を追加

update-aqua-checksums.yamlにPRレベルの排他制御を追加し、PRの更新があった場合に前のジョブをキャンセルする設定を行いました。

* fix: チェックサムの必須設定をコメントアウト

aqua.yamlファイルのチェックサム設定で、require_checksumをコメントアウトしました。

* feat: aqua-checksums.yamlでチェックサムの必須設定を有効化

- aqua.yaml: require_checksumをtrueに設定
- update-aqua-checksums.yaml: server_repositoryを追加

* feat: aqua-checksums.yamlのグローバル設定取得ステップを追加

- aqua-checksums.jsonを修正するジョブに、グローバル設定を取得するステップを追加しました。
- サーバーリポジトリの指定を、グローバル設定からの出力に変更しました。

* feat: aqua-checksums.yamlでのコミットとプッシュの条件を追加

- global-configの出力に基づいて、異なるコミットアクションを使用する条件を追加しました。

* commit changes

* feat: aqua-checksums.yamlのプルリクエストトリガーを設定し、変更検出ステップを追加

- プルリクエストのトリガー条件をaqua.yamlに変更
- aqua-checksums.jsonの変更を検出するステップを追加
- コミットとプッシュの条件に変更検出を追加

* feat: aqua-checksums.jsonファイルを削除

aqua-checksums.jsonファイルをリポジトリから削除しました。これにより、不要なチェックサム情報が整理され、管理が容易になります。

* feat: aqua-checksums.jsonの変更検出ロジックを改善

- 存在しない場合やgit管理されていない場合の変更検出を追加
- 既存ファイルの変更有無を正確に判定する条件を強化

* update: aqua-checksums.json

* feat: dictionary.txtに新しいエントリを追加

securefix、unmatch、elif、tostring、aquasecurity、reviewdog、telmateをdictionary.txtに追加しました。

* feat: aqua-checksums.jsonの変更検出ステップに名前を追加

- aqua-checksums.yamlの変更検出ステップに「Check if aqua-checksums.json is changed」という名前を追加しました。

* feat: ワークフロー名を大文字に変更

- document-pull-request.yaml: ワークフロー名を「Document Pull Request」に変更
- terraform-deploy.yaml: ワークフロー名を「Terraform Deploy」に変更
- terraform-pull-request.yaml: ワークフロー名を「Terraform Pull Request」に変更
- tfaction-root.yaml: プランワークフロー名を「Terraform Pull Request」に変更

diff --git a/.github/workflows/terraform-deploy.yaml b/.github/workflows/terraform-deploy.yaml
--- a/.github/workflows/terraform-deploy.yaml
+++ b/.github/workflows/terraform-deploy.yaml
@@ -1,4 +1,4 @@
-name: Proxmox Deploy
+name: Terraform Deploy
 on:
   push:
     branches:
@@ -285,3 +285,35 @@ jobs:
           LXC_VM_LIST: ${{needs.extract-created-lxc.outputs.lxc_vm_list}}
           HOST_FILE_LIST: ${{steps.get-script-list.outputs.HOST_FILE_LIST}}
           CONTAINER_FILE_LIST: ${{steps.get-script-list.outputs.CONTAINER_FILE_LIST}}
+
+  success:
+    needs:
+      - terraform-apply
+      - extract-created-lxc
+      - ansible-for-proxmox-lxc
+    if: ${{ always() }}
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Check job result
+        run: |
+          RESULT="${{ needs.terraform-apply.result }}"
+          if [[ $RESULT != "success" && $RESULT != "skipped" ]]; then
+            echo "This workflow failed or was cancelled!"
+            exit 1
+          fi
+
+          RESULT="${{ needs.extract-created-lxc.result }}"
+          if [[ $RESULT != "success" && $RESULT != "skipped" ]]; then
+            echo "This workflow failed or was cancelled!"
+            exit 1
+          fi
+
+          RESULT="${{ needs.ansible-for-proxmox-lxc.result }}"
+          if [[ $RESULT != "success" && $RESULT != "skipped" ]]; then
+            echo "This workflow failed or was cancelled!"
+            exit 1
+          fi
+
+          echo "Success!!"
+          exit 0
