fix: terraform-planの結果をチェックするステップを追加
成功した場合にメッセージを表示し、失敗またはキャンセルされた場合にはエラーメッセージを表示するように、successジョブのステップを修正しました。

diff --git a/.github/workflows/terraform-pull-request.yaml b/.github/workflows/terraform-pull-request.yaml
--- a/.github/workflows/terraform-pull-request.yaml
+++ b/.github/workflows/terraform-pull-request.yaml
@@ -79,8 +79,16 @@ jobs:
 
   success:
     needs: terraform-plan
-    if: ${{ !failure() }}
+    if: ${{ always() }}
     runs-on: ubuntu-latest
 
     steps:
-      - run: echo "Success!!"
+      - name: Check job result
+        run: |
+          if [[ "${{ needs.terraform-plan.result }}" == "success" ]]; then
+            echo "Terraform plan succeeded!"
+            exit 0
+          else
+            echo "Terraform plan failed or was cancelled!"
+            exit 1
+          fi
