fix: terraform-planの結果をチェックするステップを追加 (#8)
* fix: terraform-planの結果をチェックするステップを追加

成功した場合にメッセージを表示し、失敗またはキャンセルされた場合にはエラーメッセージを表示するように、successジョブのステップを修正しました。

* fix: terraform-planの結果チェックを改善

terraform-planの結果が"success"または"skipped"の場合に成功メッセージを表示するように条件を修正しました。

diff --git a/.github/workflows/terraform-pull-request.yaml b/.github/workflows/terraform-pull-request.yaml
--- a/.github/workflows/terraform-pull-request.yaml
+++ b/.github/workflows/terraform-pull-request.yaml
@@ -79,8 +79,17 @@ jobs:
 
   success:
     needs: terraform-plan
-    if: ${{ !failure() }}
+    if: ${{ always() }}
     runs-on: ubuntu-latest
 
     steps:
-      - run: echo "Success!!"
+      - name: Check job result
+        run: |
+          RESULT="${{ needs.terraform-plan.result }}"
+          if [[ $RESULT == "success" || $RESULT == "skipped" ]]; then
+            echo "Terraform plan succeeded!"
+            exit 0
+          else
+            echo "Terraform plan failed or was cancelled!"
+            exit 1
+          fi
